---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: shorten-url-demo-ingress-kube-tls
  namespace: shorten-url-demo
spec:
  dnsNames:
    - shorturl.hokamc.work
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  secretName: shorten-url-demo-ingress-kube-tls
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: shorten-url-demo
  namespace: shorten-url-demo
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`shorturl.hokamc.work`)
      services:
        - name: shorten-url-demo
          port: 443
  tls:
    secretName: shorten-url-demo-ingress-kube-tls
---